grails:
    profile: web-plugin
    codegen:
        defaultPackage: com.nayidisha.grails.uploadr
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false

# used by the demo tag
uploadr:
  defaultUploadPath:
    "${System.getProperty('user.home')}/Downloads/uploadr"
# used by the cleanUploadedFilesJob Quartz job (on ci and development)
  maxAgeUploadedFile:
        1000 * 60 * 60 * 4  # 4 hours in milliseconds
